# Generated by Django 6.0.1 on 2026-04-26 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('pain_level', models.IntegerField(default=0)),
                ('fever', models.BooleanField(default=False)),
                ('breathing_problem', models.BooleanField(default=False)),
                ('bleeding', models.BooleanField(default=False)),
                ('risk_level', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('emergency', 'Emergency')], default='normal', max_length=20)),
                ('guidance', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
